## Lab 3: Pytorch Fundamentals

### Objective
To understand the fundamentals of PyTorch, including tensor creation, manipulation, operations, and device handling (CPU/GPU), and to develop familiarity with the core building blocks used in deep learning.

### Theory
PyTorch is an open-source deep learning framework widely used for building and training neural networks. Its core data structure is the tensor, which is a multi-dimensional array similar to NumPy arrays but with GPU acceleration support.

Tensors can represent different types of data:

Scalar (0D tensor): single value

Vector (1D tensor): list of values

Matrix (2D tensor): rows and columns

Higher-dimensional tensors (ND tensors): used for images, videos, and datasets

PyTorch supports:

Mathematical operations (addition, multiplication, matrix multiplication)

Tensor reshaping and transformation

Device management (CPU/GPU)

Conversion between NumPy and PyTorch

These features form the foundation of deep learning computations.

In [88]:
!python --version

Python 3.13.0


In [89]:
# importing pytorch

import torch
torch.__version__

'2.12.0'

### 3.1. Introduction to Scalar, Vector, Matrix, and, Tensor

Tensors are the fundamental building block of machine learning. Their job is to represent data in a numerical way.

Here, you could represent an image as a tensor with shape `[3, 224, 224`] which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

Here, the tensor would have three dimensions, one each for 
- colour_channels, 
- height and 
- width.

### 3.1.1. Scalar

In [90]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [91]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


### 3.1.2. Vectors

A vector is a single dimension tensor but can contain many numbers.

In [92]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [93]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside `([)` and you only need to count one side.

### 3.1.3. Matrix

In [94]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


### 3.1.4. Tensor

In [96]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [97]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


The above `tensor`, can be the for example the following datasets: 

| Day of the week | Chiya Sales | Coffee Sales |
| :--- | :---: | ---: |
|  1 | 3 | 2 |
| 2 | 6 | 4 |
| 3 | 9 | 5 |

Or in Transposed form, we can write: 

| Day of the week | 1 | 2 |  3 |
| :--- | :---: | :---: | :---: |
| **Chiya Sales** | 3 | 6 | 9 |
| **Coffee Sales** | 2 | 4 | 5 |

![scalar_tensor](../../Old_Syllabus/Lab3-NN/images/tensor2.png)

#### 3.1.4.1 Random Tensors

In [98]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.0841, 0.0407, 0.2927],
         [0.1692, 0.7180, 0.8497]]),
 torch.float32)

In [99]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### 3.1.4.2. Tensors of only Zeros and Ones 

In [100]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [101]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### 3.1.4.3. Creating a range and tensors like

In [102]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`torch.range()` is depreciated, therefore use `torch.arange()`

In [103]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3.1.4.4. Tensor datatypes

- PyTorch offers many tensor data types, some optimized for CPUs and others for GPUs.
- Tensors associated with GPUs often use `torch.cuda` in their type or device specification.
- The default and most commonly used data type is `torch.float32` (or `torch.float`), which represents 32-bit floating-point numbers.
- Other floating-point types include:
  - `torch.float16` (`torch.half`) — 16-bit floating point
  - `torch.float64` (`torch.double`) — 64-bit floating point
- PyTorch also supports integer types with different precisions, such as:
  - 8-bit integers
  - 16-bit integers
  - 32-bit integers
  - 64-bit integers
- Integers represent whole numbers (e.g., `7`), while floating-point numbers can contain decimals (e.g., `7.0`).
- Different data types exist because of varying levels of **precision**.
- Precision determines how much detail is used to represent a number.
- Higher precision:
  - Uses more memory and computational resources
  - Provides greater numerical accuracy
- Lower precision:
  - Requires less memory
  - Computes faster
  - May reduce model accuracy or numerical precision
- Choosing a data type involves balancing computational efficiency and accuracy in deep learning and numerical computing.

In [104]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [105]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## 3.2. Getting information from tensors

The three of the most common attributes you'll want to find out about tensors are:

- `shape` - what shape is the tensor? (some operations require specific shape rules)
- `dtype` - what datatype are the elements within the tensor stored in?
- `device` - what device is the tensor stored on? (usually GPU or CPU)

In [106]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9651, 0.1463, 0.7840, 0.5581],
        [0.3456, 0.2006, 0.3991, 0.9317],
        [0.8798, 0.5932, 0.0582, 0.8999]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3.3. Tensor Operations

In deep learning, different types of data such as images, text, audio, videos, and other information are converted into **tensors** (multi-dimensional arrays of numbers).

A model learns by repeatedly performing mathematical operations on these tensors to discover patterns and relationships in the data. During training, millions of calculations may be carried out.

Some of the most common tensor operations include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

By combining these operations, (neural) networks/models can learn useful representations of data and make predictions.

In [107]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [108]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [109]:
tensor

tensor([1, 2, 3])

The operation `tensor * 10` creates a new tensor with the multiplied values, but it does not change the original `tensor`.

In [110]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [111]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [112]:
tensor

tensor([-9, -8, -7])

In [113]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


However, `torch.multiply()` also does not modify the original tensor. 

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

Note: 
- Inner dimensions should match
- Resulting matrix has the shape of the outer dimensions

For example: `(2, 3)` @ `(3, 2)` -> `(2, 2)`

In [114]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


[1, 2, 3] · [1, 2, 3] 

= (1×1) + (2×2) + (3×3) 

= 1 + 4 + 9 

= 14

The main two rules for matrix multiplication to remember are:
1. The inner dimensions must match: (2,3) @ (3,2) 
2. The resulting matrix has the shape of the outer dimensions: (2,3) @ (3,2) -> (2,2)

`@` in Python is the symbol for matrix multiplication.

**One of the most common errors in deep learning (shape errors)**

In [115]:


tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [116]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


**Finding the min, max, mean, sum, etc (aggregation)**

In [117]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


**Positional min/max**


In [118]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Change tensor datatype**

In [119]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

**Reshaping**

- `torch.reshape(input, shape)`:	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

In [120]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [121]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

**View**

- `Tensor.view(shape)`:	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [122]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [123]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [124]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [125]:
import torch
x = torch.arange(6)
# print(x,x.shape)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


That's the exact reason both functions exist: `view()` is a strict **"reinterpret the existing memory"** operation, while `reshape()` is a flexible **"give me this shape, even if a copy is needed"** operation.

**Stack**

- `torch.stack(tensors, dim=0)`:	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [126]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [127]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

**Squeeze and Unsqueeze funtions.**

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [128]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


**permute**

- `torch.permute()` is used to rearrange the order of a tensor's dimensions (axes) without changing the underlying data values.

In [129]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


**Note**: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

## 3.4. Indexing


In [130]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [131]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## 3.5. Pytorch Tensor to NumPy arrays and vice versa

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [132]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [133]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 3.6. Tensors on GPU

In [134]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [135]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [136]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [137]:
# Count number of devices
torch.cuda.device_count()

0

In [138]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [139]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Discussion
This lab taught us about the basics of PyTorch tensors. PyTorch tensors are the data structure used in deep learning. We learned about kinds of PyTorch tensors like scalars, vectors, matrices and higher-dimensional PyTorch tensors. This helped us understand how we can use numbers to show real-world data.

The lab showed us how to do operations with PyTorch tensors like adding, multiplying and multiplying matrices. We also learned about reshaping, stacking and indexing PyTorch tensors. We saw that it is easy to do operations on each element of a PyTorch tensor. Multiplying matrices is harder because the numbers of elements in each row and column have to match. We can use transpose to fix problems with the shape of PyTorch tensors.

We also learned about things to know about PyTorch tensors, like their shape what kind of data they hold and where they are stored. These things are necessary, for doing calculations. We found out that we can easily change PyTorch tensors into NumPy arrays and vice versa which means that different libraries can work together.

Finally we learned about using the GPU with PyTorch tensors. We saw how we can move PyTorch tensors from the CPU to the GPU to make calculations faster. Even though we did this lab on a CPU it was still good to learn about using the GPU with PyTorch tensors.

### Conclusion
This lab was really helpful in learning the basics of PyTorch and working with tensors.

It showed me  data is handled, changed and used with tensors.

Key things I learned include:

How to work with tensor shapes

The rules for multiplying matrices

How to change the shape of tensors

How to handle devices

These skills are really important for creating and fixing learning models.
Overall this lab gave me a base to learn more about machine learning and neural networks using PyTorch.
It covered the fundamentals of PyTorch and tensor operations.
PyTorch and tensor operations are really important for building models.
The lab helped in understanding how data is represented manipulated and processed using tensors and PyTorch.

PyTorch is a tool, for building and debugging deep learning models.